# pull a HOST OS
FROM ubuntu:latest

# directory in container, where app will be placed
WORKDIR /usr/src/app

# install nginx
RUN apt-get update
RUN apt-get install nginx -y

# pull Base OS
FROM node:14-alpine

# get config files from app and place them in container
COPY rollup.config.js ./
COPY package*.json ./

# install dependencies from app
RUN npm install

# get app and place in container
COPY ./src ./src
COPY ./public ./public

# build production files of app
RUN npm run-script build

#PORT
EXPOSE 5000

# server ip
#ENV HOST=0.0.0.0

# start nginx
CMD ["nginx","-g","daemon off;", "npm", "start"]

#Error: Cannot find module '/nginx'